apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: nginx-dev
spec:
  stack: dev  # Uses the dev stack configuration
  projectRepo: https://github.com/perzefi/nginx-client  # Replace with your actual repo
  branch: main
  destroyOnFinalize: false  # Keep resources when the Stack CR is deleted
  config:  # You can override config here too (optional)
    nginx-deployment:appName: nginx-dev
  secretsProvider: "kubernetes"
  envRefs:
    pulumiAccessToken:
      type: Secret
      secret:
        name: pulumi-api-secret
        key: PULUMI_ACCESS_TOKEN